# Stage 1: Setup Nginx
FROM nginx:1.21-alpine

# Копирование конфигурации Nginx
COPY ./config/prod/nginx.conf /etc/nginx/nginx.conf


# Копирование SSL сертификатов
COPY ./certificate.crt /etc/nginx/certs/
COPY ./private.key /etc/nginx/certs/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
